name: Code formatting

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push or pull request, but only for the main branch
  push:
    branches:
      - "*"
      - "**"
      - "!publication"
  pull_request: {}

jobs:
  pep8-check-flake8:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: pip install flake8 && pip list
        shell: bash
      - name: PEP8
        run: |
          flake8 .

  imports-check-isort:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install isort
        run: pip install isort && pip list
      - name: isort
        run: |
          isort . --check --diff

  format-check-yapf:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install yapf && pip list
        shell: bash
      - name: yapf
        run: |
          yapf --diff --parallel --recursive .

  pre-commit-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: set PY
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - uses: pre-commit/action@v2.0.2
        # this action also provides an additional behaviour when used in private repositories
        # when configured with a github token, the action will push back fixes to the pull request branch
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
