name: CI testing

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push or pull request, but only for the main branch
  pull_request:
    paths-ignore:
      - .actions/**
      - .github/**
      - .notebooks/*.ipynb
      - .notebooks/**/*.ipynb
      - docs/**

jobs:
  treon:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.8]
    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 55

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # fetch all history for all branches and tags
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip --version
          pip install --requirement requirements.txt --find-links https://download.pytorch.org/whl/cpu/torch_stable.html
          pip list
        shell: bash

      - name: Process folders
        id: changed
        run: |
          head=$(git rev-parse origin/"${{ github.base_ref }}")
          git diff --name-only $head --output=master-diff.txt
          python .actions/helpers.py group-folders master-diff.txt
          python -c "lines = open('changed-folders.txt').readlines(); print(f'::set-output name=dirs::{len(lines)}')"
        shell: bash

      - name: Generate notebook
        if: steps.changed.outputs.dirs != 0
        run: |
          while IFS= read -r line; do
              bash .actions/ipynb-generate.sh $line
          done <<< $(cat changed-folders.txt)
        shell: bash

      - name: Treon notebook
        if: steps.changed.outputs.dirs != 0
        run: |
          while IFS= read -r line; do
              bash .actions/ipynb-test.sh $line
          done <<< $(cat changed-folders.txt)
        shell: bash
